modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="findblocks"
version="1.0.0"
displayName="findblocks"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="brandon, MCreator"

[[dependencies.findblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



